doctrine:
  dbal:
    charset: UTF8
    url: '%env(resolve:DATABASE_URL)%'
    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '5.7'
    types:
      json: Sonata\Doctrine\Types\JsonType
      datetime_immutable: \Carbon\Doctrine\DateTimeImmutableType
      datetime: \Carbon\Doctrine\DateTimeType
      carbon_immutable: \Carbon\Doctrine\CarbonImmutableType
      carbon: \Carbon\Doctrine\CarbonType
    mapping_types:
      enum: string
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      ApplicationSonataUserBundle: ~
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
      loggable:
        type: annotation
        alias: Gedmo
        prefix: Gedmo\Loggable\Entity
        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
    filters:
      softdeletable:
        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
        enabled: true