# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
    view:
        view_response_listener:  true
    exception:
        enabled: true
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: ^/api/v1, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }
    versioning:
        enabled: true
#        resolvers:
#            query: true # Query parameter: /users?version=v1
#            custom_header: true # X-Accept-Version header
#            media_type:
#                enabled: true
#                regex: '/api\/(v|version)=(?P<version>[0-9\.]+)/'
#        guessing_order:
#            - query
#            - custom_header
#            - media_type