sonata_user:
  class:
    user: App\Application\Sonata\UserBundle\Entity\User
    group: App\Application\Sonata\UserBundle\Entity\Group
  admin:
    group:
      class: App\Admin\GroupAdmin
      controller: App\Controller\GroupAdminController
      translation: messages
  security_acl: false
  manager_type: orm # can be orm or mongodb
  impersonating:
    route: sonata_admin_dashboard