twig:
  default_path: '%kernel.project_dir%/templates'
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  exception_controller: null
  paths:
    '%kernel.project_dir%/assets/css': css
    '%kernel.project_dir%/assets/images': images
  form_themes:
      - '@SonataForm/Form/datepicker.html.twig'