sonata_user_admin_security:
  resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
  prefix: /admin

sonata_user_admin_resetting:
  resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
  prefix: /admin/resetting

api_login_check:
  path: /api/v1/login_check

#api_auth_login:
#  path: /api/auth/login
#  methods:  [POST]