nelmio_api_doc:
    documentation:
        info:
            title: Covid RCP App
            description: Web app para diagnóstico y predicción de complicaciones COVID-19
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
        host_patterns:
            - ^api\.